version: '3.8'
services:
  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    # Optional: Adjust resource constraints
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '4.0'
    #       memory: 16G
